### ISSUE TITLE
Facebook Auth undefined

### ISSUE THREAD

**Issue by gustafbrunlf** [DaftMonk/generator-angular-fullstack#1404] opened 2015-11-02 12:04 UTC
Hi, 
I've been trying to setup Facebook Auth login but I somehow get the following error:

/Applications/MAMP/htdocs/campforfree/server/auth/facebook/passport.js:21
            email: profile.emails[0].value,
                                 ^
TypeError: Cannot read property '0' of undefined

any ideas would be appreciated!

**Comment by Awk34** [comment] 2015-11-02 15:54
Possible duplicate of #1390 or #1186

**Comment by gardner** [comment] 2015-11-07 16:51
My facebook account does not have an email associated with it. I fixed this by changing ``server/auth/facebook/passport.js`` to check the existence of an email address before attempting to access it. The code looks like:

    var passport = require('passport');
    var FacebookStrategy = require('passport-facebook').Strategy;

    exports.setup = function (User, config) {
      passport.use(new FacebookStrategy({
          clientID: config.facebook.clientID,
          clientSecret: config.facebook.clientSecret,
          callbackURL: config.facebook.callbackURL
        },
        function(accessToken, refreshToken, profile, done) {
          User.findOne({
            'facebook.id': profile.id
          },
          function(err, user) {
            if (err) {
              return done(err);
            }
            var email = '';
            if (profile.emails && profile.emails[0]) {
              email = profile.emails[0].value;
            }
        
            if (!user) {
              user = new User({
                name: profile.displayName,
                email: email,
                role: 'player',
                username: profile.username,
                provider: 'facebook',
                facebook: profile._json
              });
              user.save(function(err) {
                if (err) return done(err);
                done(err, user);
              });
            } else {
              return done(err, user);
            }
          })
        }
      ));
    };

**Comment by gardner** [comment] 2015-11-07 16:59
I just created a pull request with a smaller code change that does the same thing: https://github.com/DaftMonk/generator-angular-fullstack/pull/1414

**Comment by Awk34** [comment] 2015-11-07 19:48
@gardner please change your `auth/facebook/passport.js` to look like this one: https://github.com/DaftMonk/generator-angular-fullstack/blob/master/app/templates/server/auth(auth)/facebook(facebookAuth)/passport.js

**Closed** 2015-11-07 20:33 UTC
Labels: question

**Comment by gardner** [comment] 2015-11-12 12:07
My Facebook account does not have an email associated with it. When my ``auth/facebook/passport.js`` looks like the one that you posted, I experience a crash with a stackdump and the error listed in this bug.

**Comment by Awk34** [comment] 2015-11-12 16:41
In the current state of the generator, it requires email addresses. Of course, it shouldn't crash the app if a user doesn't have an email address.

To really fix this, things would have to be re-worked to use a different identifying property, such as a username.
